check-leaks: false
color: true
diff: true
full-trace: true
reporter: dot
require: 'ts-node/register'
timeout: 10000
v8-stack-trace-limit: 100

#extension:
#  - 'ts'
#node-option:
#  - 'experimental-specifier-resolution=node'
#  - 'loader=ts-node/esm'
